// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.proto

package api

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Measurement struct {
	Value                float64  `protobuf:"fixed64,1,opt,name=Value,proto3" json:"Value,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Unit                 string   `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Measurement) Reset()         { *m = Measurement{} }
func (m *Measurement) String() string { return proto.CompactTextString(m) }
func (*Measurement) ProtoMessage()    {}
func (*Measurement) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}
func (m *Measurement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Measurement.Unmarshal(m, b)
}
func (m *Measurement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Measurement.Marshal(b, m, deterministic)
}
func (m *Measurement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Measurement.Merge(m, src)
}
func (m *Measurement) XXX_Size() int {
	return xxx_messageInfo_Measurement.Size(m)
}
func (m *Measurement) XXX_DiscardUnknown() {
	xxx_messageInfo_Measurement.DiscardUnknown(m)
}

var xxx_messageInfo_Measurement proto.InternalMessageInfo

func (m *Measurement) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Measurement) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Measurement) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

type GetHistoryRequest struct {
	From                 int64    `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Until                int64    `protobuf:"varint,2,opt,name=until,proto3" json:"until,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHistoryRequest) Reset()         { *m = GetHistoryRequest{} }
func (m *GetHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetHistoryRequest) ProtoMessage()    {}
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}
func (m *GetHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoryRequest.Unmarshal(m, b)
}
func (m *GetHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoryRequest.Marshal(b, m, deterministic)
}
func (m *GetHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoryRequest.Merge(m, src)
}
func (m *GetHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetHistoryRequest.Size(m)
}
func (m *GetHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoryRequest proto.InternalMessageInfo

func (m *GetHistoryRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *GetHistoryRequest) GetUntil() int64 {
	if m != nil {
		return m.Until
	}
	return 0
}

type GetHistoryResponse struct {
	Values               []float64 `protobuf:"fixed64,1,rep,packed,name=Values,proto3" json:"Values,omitempty"`
	Unit                 string    `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetHistoryResponse) Reset()         { *m = GetHistoryResponse{} }
func (m *GetHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetHistoryResponse) ProtoMessage()    {}
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}
func (m *GetHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoryResponse.Unmarshal(m, b)
}
func (m *GetHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoryResponse.Marshal(b, m, deterministic)
}
func (m *GetHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoryResponse.Merge(m, src)
}
func (m *GetHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetHistoryResponse.Size(m)
}
func (m *GetHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoryResponse proto.InternalMessageInfo

func (m *GetHistoryResponse) GetValues() []float64 {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *GetHistoryResponse) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

type UpdatePositionRequest struct {
	Position             float64  `protobuf:"fixed64,1,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePositionRequest) Reset()         { *m = UpdatePositionRequest{} }
func (m *UpdatePositionRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePositionRequest) ProtoMessage()    {}
func (*UpdatePositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}
func (m *UpdatePositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePositionRequest.Unmarshal(m, b)
}
func (m *UpdatePositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePositionRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePositionRequest.Merge(m, src)
}
func (m *UpdatePositionRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePositionRequest.Size(m)
}
func (m *UpdatePositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePositionRequest proto.InternalMessageInfo

func (m *UpdatePositionRequest) GetPosition() float64 {
	if m != nil {
		return m.Position
	}
	return 0
}

type UpdatePositionResponse struct {
	ReachedPosition      float64  `protobuf:"fixed64,1,opt,name=reached_position,json=reachedPosition,proto3" json:"reached_position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePositionResponse) Reset()         { *m = UpdatePositionResponse{} }
func (m *UpdatePositionResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePositionResponse) ProtoMessage()    {}
func (*UpdatePositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}
func (m *UpdatePositionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePositionResponse.Unmarshal(m, b)
}
func (m *UpdatePositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePositionResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePositionResponse.Merge(m, src)
}
func (m *UpdatePositionResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePositionResponse.Size(m)
}
func (m *UpdatePositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePositionResponse proto.InternalMessageInfo

func (m *UpdatePositionResponse) GetReachedPosition() float64 {
	if m != nil {
		return m.ReachedPosition
	}
	return 0
}

type GetPositionResponse struct {
	Position             float64  `protobuf:"fixed64,1,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPositionResponse) Reset()         { *m = GetPositionResponse{} }
func (m *GetPositionResponse) String() string { return proto.CompactTextString(m) }
func (*GetPositionResponse) ProtoMessage()    {}
func (*GetPositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}
func (m *GetPositionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPositionResponse.Unmarshal(m, b)
}
func (m *GetPositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPositionResponse.Marshal(b, m, deterministic)
}
func (m *GetPositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPositionResponse.Merge(m, src)
}
func (m *GetPositionResponse) XXX_Size() int {
	return xxx_messageInfo_GetPositionResponse.Size(m)
}
func (m *GetPositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPositionResponse proto.InternalMessageInfo

func (m *GetPositionResponse) GetPosition() float64 {
	if m != nil {
		return m.Position
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "api.Empty")
	proto.RegisterType((*Measurement)(nil), "api.Measurement")
	proto.RegisterType((*GetHistoryRequest)(nil), "api.GetHistoryRequest")
	proto.RegisterType((*GetHistoryResponse)(nil), "api.GetHistoryResponse")
	proto.RegisterType((*UpdatePositionRequest)(nil), "api.UpdatePositionRequest")
	proto.RegisterType((*UpdatePositionResponse)(nil), "api.UpdatePositionResponse")
	proto.RegisterType((*GetPositionResponse)(nil), "api.GetPositionResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x41, 0xae, 0xd3, 0x30,
	0x10, 0x95, 0x1b, 0xf2, 0xf9, 0x9d, 0x4a, 0x90, 0xfa, 0xd3, 0x12, 0xa5, 0x08, 0x45, 0x5e, 0x05,
	0x16, 0x8d, 0x68, 0x77, 0x48, 0x48, 0x40, 0x85, 0x0a, 0x42, 0x08, 0x88, 0x04, 0x0b, 0x36, 0xc8,
	0xb4, 0x6e, 0x6b, 0x29, 0xb1, 0x8d, 0xed, 0x2c, 0xba, 0xe5, 0x0a, 0x5c, 0x84, 0x35, 0xd7, 0xe0,
	0x0a, 0x1c, 0x04, 0xc5, 0x49, 0xdb, 0xd0, 0x56, 0xdd, 0xcd, 0x3c, 0xcf, 0xbc, 0x79, 0xf3, 0x46,
	0x86, 0x2e, 0x55, 0x7c, 0xac, 0xb4, 0xb4, 0x12, 0x7b, 0x54, 0xf1, 0xe8, 0xc1, 0x5a, 0xca, 0x75,
	0xce, 0x52, 0xaa, 0x78, 0x4a, 0x85, 0x90, 0x96, 0x5a, 0x2e, 0x85, 0xa9, 0x4b, 0xc8, 0x6d, 0xf0,
	0x5f, 0x15, 0xca, 0x6e, 0xc9, 0x5b, 0xe8, 0xbd, 0x63, 0xd4, 0x94, 0x9a, 0x15, 0x4c, 0x58, 0x7c,
	0x0f, 0xfc, 0xcf, 0x34, 0x2f, 0x59, 0x88, 0x62, 0x94, 0xa0, 0xac, 0x4e, 0x30, 0x86, 0x5b, 0x96,
	0x17, 0x2c, 0xec, 0xc4, 0x28, 0xf1, 0x32, 0x17, 0x57, 0x58, 0x29, 0xb8, 0x0d, 0xbd, 0x18, 0x25,
	0xdd, 0xcc, 0xc5, 0xe4, 0x19, 0xf4, 0xe7, 0xcc, 0xbe, 0xe6, 0xc6, 0x4a, 0xbd, 0xcd, 0xd8, 0xf7,
	0x92, 0x19, 0x5b, 0x15, 0xae, 0xb4, 0x2c, 0x1c, 0xa3, 0x97, 0xb9, 0xb8, 0x1a, 0x53, 0x0a, 0xcb,
	0xf3, 0x86, 0xb1, 0x4e, 0xc8, 0x73, 0xc0, 0xed, 0x76, 0xa3, 0xa4, 0x30, 0x0c, 0x0f, 0xe1, 0xca,
	0xa9, 0x30, 0x21, 0x8a, 0xbd, 0x04, 0x65, 0x4d, 0xb6, 0x17, 0xd0, 0x69, 0x09, 0x98, 0xc2, 0xe0,
	0x93, 0x5a, 0x52, 0xcb, 0x3e, 0x48, 0xc3, 0xab, 0x7d, 0x77, 0x22, 0x22, 0xb8, 0x56, 0x0d, 0xd4,
	0xac, 0xb6, 0xcf, 0xc9, 0x0c, 0x86, 0xc7, 0x4d, 0xcd, 0xe8, 0x47, 0x10, 0x68, 0x46, 0x17, 0x1b,
	0xb6, 0xfc, 0x7a, 0xd4, 0x7d, 0xb7, 0xc1, 0x77, 0x2d, 0xe4, 0x09, 0xdc, 0xcc, 0x99, 0x3d, 0x61,
	0xb8, 0x30, 0x77, 0xf2, 0x0b, 0x01, 0xcc, 0xa4, 0xb0, 0x5a, 0xe6, 0x39, 0xd3, 0xf8, 0x23, 0xf4,
	0x6b, 0x19, 0xed, 0x7b, 0x04, 0xe3, 0xea, 0xac, 0x2d, 0x24, 0x02, 0x87, 0xd4, 0xc7, 0x7b, 0xf8,
	0xe3, 0xcf, 0xdf, 0x9f, 0x9d, 0x90, 0xdc, 0xa4, 0xc5, 0xa1, 0x22, 0x2d, 0x1d, 0xcb, 0x53, 0xf4,
	0x18, 0xbf, 0x07, 0x38, 0x18, 0x8a, 0x87, 0xae, 0xf3, 0xe4, 0x40, 0xd1, 0xfd, 0x13, 0xbc, 0x16,
	0x4f, 0x02, 0x47, 0x0f, 0xf8, 0x3a, 0xdd, 0xd4, 0x2f, 0x93, 0xdf, 0x08, 0xfc, 0x17, 0x0b, 0x2b,
	0x35, 0x5e, 0xc1, 0x9d, 0xff, 0x4d, 0xc3, 0x91, 0xa3, 0x39, 0x6b, 0x7f, 0x34, 0x3a, 0xfb, 0xd6,
	0x8c, 0x19, 0xb9, 0x31, 0x03, 0x12, 0xa4, 0x3b, 0x6b, 0x5a, 0x2b, 0xbc, 0x81, 0x5e, 0xcb, 0x57,
	0xdc, 0xda, 0xfe, 0x32, 0x69, 0xdf, 0x91, 0xf6, 0x70, 0x77, 0x4f, 0xfa, 0xd2, 0xff, 0x52, 0x7d,
	0x8c, 0x6f, 0x57, 0xee, 0x07, 0x4c, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x29, 0xa6, 0x2d, 0x20,
	0x31, 0x03, 0x00, 0x00,
}
