from golang:alpine
Maintainer the_l1ne@gmx.de
WORKDIR /usr/local/go/src/github.com/TheL1ne/Sensor_Aktor_controller/
# escape=`

ENV Source_Path 'C:\Users\The L!ne\go\src\github.com\TheL1ne\Sensor_Aktor_controller'

COPY  api /usr/local/go/src/github.com/TheL1ne/Sensor_Aktor_controller/
COPY  actor /usr/local/go/src/github.com/TheL1ne/Sensor_Aktor_controller/

# RUN go build ./actor
EXPOSE 8080
CMD ["actor"]